# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: terraform-backend-kv
- group: lib-petclinic
- name: TF_VAR_key
  value: $(Build.Repository.Name).tfstate

stages:
  - stage: terraform
    jobs:
    - job: do_terraform
      steps:
      - task: FuncToolsInstaller@0
        displayName: "Install Function Tool"
      - script: terraform --version
        displayName: 'check terraform version'
      - task: AzureCLI@2
        displayName: "Terraform Init"
        inputs:
          azureSubscription: ARM_SUBSCRIPTION
          scriptType: bash
          addSpnToEnvironment: true
          scriptLocation: inlineScript
          inlineScript: |
            echo "starting..."
            cd terraform
            export ARM_CLIENT_ID=$servicePrincipalId
            export ARM_CLIENT_SECRET=$servicePrincipalKey
            export ARM_TENANT_ID=$tenantId
            ./env_setup.sh
            terraform init --backend-config=backend.tfvars
        env:
          TF_VAR_subscription_id: $(subscription-id)
          TF_VAR_storage_account_name: $(storage-account-name)
          TF_VAR_resource_group_name: $(resource-group-name)
          TF_VAR_key: $(TF_VAR_key)
          TF_VAR_container_name: $(container-name)
          TF_VAR_app_insights_name: $(app-insights-name)
          TF_VAR_app_insights_rg: $(app-insights-rg)
          TF_VAR_app_base_url: $(app-base-url)
      - task: AzureCLI@2
        displayName: "Terraform Plan"
        inputs:
          azureSubscription: ARM_SUBSCRIPTION
          scriptType: bash
          addSpnToEnvironment: true
          scriptLocation: inlineScript
          inlineScript: |
            echo "starting..."
            cd terraform
            export ARM_CLIENT_ID=$servicePrincipalId
            export ARM_CLIENT_SECRET=$servicePrincipalKey
            export ARM_TENANT_ID=$tenantId
            terraform plan -out theplan
        env:
          TF_VAR_subscription_id: $(subscription-id)
          TF_VAR_storage_account_name: $(storage-account-name)
          TF_VAR_resource_group_name: $(resource-group-name)
          TF_VAR_key: $(TF_VAR_key)
          TF_VAR_container_name: $(container-name)
          TF_VAR_app_insights_name: $(app-insights-name)
          TF_VAR_app_insights_rg: $(app-insights-rg)
          TF_VAR_app_base_url: $(app-base-url)
      - task: AzureCLI@2
        displayName: "Terraform Apply"
        inputs:
          azureSubscription: ARM_SUBSCRIPTION
          scriptType: bash
          addSpnToEnvironment: true
          scriptLocation: inlineScript
          inlineScript: |
            echo "starting..."
            cd terraform
            export ARM_CLIENT_ID=$servicePrincipalId
            export ARM_CLIENT_SECRET=$servicePrincipalKey
            export ARM_TENANT_ID=$tenantId
            mv pctrackavailability/local.settings.json.sample pctrackavailability/local.settings.json
            terraform apply -auto-approve theplan
        env:
          TF_VAR_subscription_id: $(subscription-id)
          TF_VAR_storage_account_name: $(storage-account-name)
          TF_VAR_resource_group_name: $(resource-group-name)
          TF_VAR_key: $(TF_VAR_key)
          TF_VAR_container_name: $(container-name)
          TF_VAR_app_insights_name: $(app-insights-name)
          TF_VAR_app_insights_rg: $(app-insights-rg)
          TF_VAR_app_base_url: $(app-base-url)
